const productosRiver = [
  {
    nombre: "Remera River Plate Titular 2023",
    id: "RP-REM-2023-X1Z",
    precio: 12500,
    descripcion: "Remera titular oficial de River Plate temporada 2023",
    category: "hombre",
    imagen: "https://todo-online.com.ar/1103-large_default/camiseta-river-plate-titular-2023-2024.jpg",
    stock: 5,
  },
  {
    nombre: "Pantalón de Entrenamiento River Plate",
    id: "RP-PAN-2023-A9B",
    precio: 9500,
    descripcion: "Pantalón de entrenamiento negro con el escudo de River Plate",
    category: "hombre",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCxPcVl-AhLfYHt4od6XF714KkZtZg6PvsiQ&s",
    stock: 12,
  },
  {
    nombre: "Zapatillas Adidas River Plate",
    id: "RP-ZAP-2023-L4K",
    precio: 18000,
    descripcion: "Zapatillas deportivas River Plate",
    category: "calzados",
    imagen: "https://www.fullram.com.ar/files/products/5fdb509c09390-2115-4.jpg",
    stock: 9,
  },
  {
    nombre: "Buzo River Plate 2023",
    id: "RP-TROL-2024-PT",
    precio: 13500,
    descripcion: "Buzo oficial de River Plate",
    category: "hombre",
    imagen: "https://www.digitalsport.com.ar/files/products/63cac72bd4004-574762-500x500.jpg",
    stock: 1,
  },
  {
    nombre: "Remera River Plate Mujer 2023",
    id: "RP-REM-MUJER-2023",
    precio: 13000,
    descripcion: "Remera oficial de River Plate para mujer, temporada 2023.",
    category: "mujer",
    imagen: "https://www.dexter.com.ar/on/demandware.static/-/Sites-365-dabra-catalog/default/dw7d96dd43/products/ADGB7589/ADGB7589-3.JPG",
    stock: 7,
  },
  {
    nombre: "Pantalón de Entrenamiento River Plate Mujer",
    id: "RP-PAN-MUJER-2023",
    precio: 9800,
    descripcion: "Pantalón de entrenamiento negro con el escudo de River Plate, para mujer.",
    category: "mujer",
    imagen: "https://media2.solodeportes.com.ar/media/catalog/product/cache/3cb7d75bc2a65211451e92c5381048e9/p/a/pantalon-de-river-adidas-entrenamiento-condivo-22-mujer-verde-100020hc1054001-1.jpg",
    stock: 15,
  },
];

export default productosRiver;
